# RESTFULIE-PY

# SETUP

PYTHON="python"
EASYINSTALL="easy_install"
NOSETESTS="nosetests"

# TARGETS

all: test install

dev: devinstall test

console:
	${PYTHON}

deps:
	${EASYINSTALL} httplib2
	${EASYINSTALL} nose
	${EASYINSTALL} mockito

devinstall: deps
	${PYTHON} setup.py develop

install:
	${PYTHON} setup.py install

test:
	${PYTHON} test/httpserver.py > /dev/null 2> /dev/null &
	${NOSETESTS} test
	curl http://localhost:20144/stop > /dev/null 2> /dev/null
	
.PHONY: deps devinstall install test
